services:
  - type: web
    name: finance-tracker-fullstack
    env: node
    plan: free
    region: oregon
    buildCommand: |
      cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node index.js
    rootDir: backend
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: PROJ_ENV
        value: production
      - key: JWT_SECRET
        value: yehJawaniHaiDeewani
      - key: MONGO_URI
        value: mongodb+srv://RonakNangia:sYnHcI0F54MjI9xX@chatappcluster.sw7ab.mongodb.net/FinanceTrackerDb?retryWrites=true&w=majority&appName=chatAppCluster
    autoDeploy: true
